CREATE TABLE "equipamentos" (
	"id" serial PRIMARY KEY NOT NULL,
	"executionId" integer,
	"downloadId" integer,
	"processo" varchar(32) NOT NULL,
	"numeroRegistro" varchar(64),
	"nomeProduto" varchar(512),
	"nomeTecnico" text,
	"situacao" varchar(128),
	"cnpjEmpresa" varchar(18),
	"razaoSocial" text,
	"autorizacaoEmpresa" varchar(32),
	"riscoSigla" varchar(16),
	"riscoDescricao" varchar(128),
	"vencimentoDescricao" varchar(128),
	"vencimentoVencido" varchar(8),
	"dataInicioVigencia" timestamp,
	"dataVencimento" timestamp,
	"dataCancelamento" timestamp,
	"cancelado" varchar(8),
	"tipoAnexo" varchar(256),
	"nomeArquivo" varchar(512),
	"dataEnvioAnexo" timestamp,
	"pdfUrl" text,
	"b2MetaKey" varchar(512),
	"fabricantesJson" text,
	"metadataJson" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
